version: '3.8'

services:
  ips-gym:
    image: nginx:alpine
    volumes:
      - /opt/ips-gym/html:/usr/share/nginx/html:ro
    networks:
      - Rodrigo
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.ips-gym.rule=Host(`ipsbiomecanic.liveuni.com.br`)
        - traefik.http.routers.ips-gym.entrypoints=websecure
        - traefik.http.routers.ips-gym.tls.certresolver=letsencryptresolver
        - traefik.http.services.ips-gym.loadbalancer.server.port=80

networks:
  Rodrigo:
    external: true
